### ISSUE TITLE
可以编译多一个带广告功能的插件不，固件

### ISSUE THREAD

**Issue by 553051957** [FishInShallow/Padavan_RM2100#1]
可以编译多一个带广告功能的插件不，固件，谢谢

**Comment by FishInShallow** [comment]
你可以先fork，根据自己需要修改RM2100.config配置文件，想开什么开什么

**Comment by 553051957** [comment]
配置文件，有问题，编译成功，广告插件启动后，没有显示规则数量bug，出国插件偶尔出现bug，这些问题在此配置文件有问题，用另外配置文件，来编译，没有任何的问题发自我的 iPad在 2023年9月13日，13:25，FishInShallow ***@***.***> 写道：﻿
你可以先fork，根据自己需要修改RM2100.config配置文件，想开什么开什么
