### ISSUE TITLE
出国软件运行成功，广告软件bug

### ISSUE THREAD

**Issue by 553051957** [FishInShallow/Padavan_RM2100#2]
出国软件运行成功，看油管入谷歌地反应，广告插件运行成功，广告规则没有显示规则数量

**Comment by FishInShallow** [comment]
请提供一下你的配置文件，详细描述遇到的问题。几个月前你说使用别的配置文件，没有任何问题，我以为你已经解决了。

**Comment by 553051957** [comment]
> 请提供一下你的配置文件，详细描述遇到的问题。几个月前你说使用别的配置文件，没有任何问题，我以为你已经解决了。

同款机器，出国软件是打开，也是无法出国和上去油管，机场没有任何问题，就是打开广告插件功能没有显示规则数量，然后尝试去广告也是无效，配置文件也是你的提供，后面我就是去找h大的源码和配置文件来验证没有任何的问题

**Comment by 553051957** [comment]
> 请提供一下你的配置文件，详细描述遇到的问题。几个月前你说使用别的配置文件，没有任何问题，我以为你已经解决了。

不过也是谢谢你，支持下，我也是尝试过你编译固件刷进去机器也是同样的问题，自己编译固件的问题一模一样

**Comment by FishInShallow** [comment]
我目前使用的就是9月13号编译的那个包，插件我只用ShadowSocksR，这个我是正常使用的，没法验证你遇到的其它问题。而且在[MeIsReallyBa/padavan-4.4](https://github.com/MeIsReallyBa/padavan-4.4)的基础上，我只修改了ShadowSocksR以支持xray1.8，应该不会影响其它插件，除非原版就有这些问题。如果是这样，可能我需要使用旧版本的固件去修改了，你用的是这个吗
[hanwckf/rt-n56u](https://github.com/hanwckf/rt-n56u)

**Comment by 553051957** [comment]
> 我目前使用的就是9月13号编译的那个包，插件我只用ShadowSocksR，这个我是正常使用的，没法验证你遇到的其它问题。而且在[MeIsReallyBa/padavan-4.4](https://github.com/MeIsReallyBa/padavan-4.4)的基础上，我只修改了ShadowSocksR以支持xray1.8，应该不会影响其它插件，除非原版就有这些问题。如果是这样，可能我需要使用旧版本的固件去修改了，你用的是这个吗 [hanwckf/rt-n56u](https://github.com/hanwckf/rt-n56u)

我使用
chongshengB和[MeIsReallyBa/padavan-4.4]来编译没有任何的问题，目前我用到，就是我说两个固件自编译来测试过没有问题，https://github.com/553051957/Padavan-build此大佬都是没有问题，两个源码都是用到MeIsReallyBa大佬来编译没问题，你的源码我看下也是来MeIsReallyBa大佬来编译老是出现我提到问题，用到你的配置文件，自编译chongshengB和[MeIsReallyBa/padavan-4.4]来都是没有任何的问题

**Comment by FishInShallow** [comment]
我测试了一下，如你所说。原因是curl没有启用，下载规则文件失败。
### RM2100.config
```
CONFIG_FIRMWARE_INCLUDE_HTTPS=y
CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC=y
CONFIG_FIRMWARE_INCLUDE_CURL=y
```
[2023.10.25-2111-test](https://github.com/FishInShallow/Padavan_RM2100/releases/tag/2023.10.25-2111-test)

**Comment by 553051957** [comment]
> 我测试了一下，如你所说。原因是curl没有启用，下载规则文件失败。
> 
> ### RM2100.config
> ```
> CONFIG_FIRMWARE_INCLUDE_HTTPS=y
> CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC=y
> CONFIG_FIRMWARE_INCLUDE_CURL=y
> ```
> 
> [2023.10.25-2111-test](https://github.com/FishInShallow/Padavan_RM2100/releases/tag/2023.10.25-2111-test)

ok.出国软件不支持我的另外节点，xray此插件是全功能。我用openwrt也是不支持此节点，太奇怪，但是我用到另外编译固件就是支持
